# This is a basic workflow to help you get started with Actions

name: build codelab-elements

#name: Go

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      BAZEL: 0.18.1
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.11

    - name: Install Bazel
      run: |
        wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL}/bazel-${BAZEL}-installer-linux-x86_64.sh"
        chmod +x install.sh
        ./install.sh --user
        rm -f install.sh

    - name: install go mods
      run: |
        go get golang.org/x/lint/golint
        go get -u github.com/golang/protobuf/protoc-gen-go
        curl -OL https://github.com/google/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip
        sudo unzip -o protoc-3.7.1-linux-x86_64.zip -d /usr/local bin/protoc
        sudo unzip -o protoc-3.7.1-linux-x86_64.zip -d /usr/local include/*
        rm -f protoc-3.7.1-linux-x86_64.zip
        go get -t -d ./claat/...

    - name: Claat test lint
      run: make -C claat test lint

    - name: Claat test lint
      run: bash codelab-elements/tools/ci-presubmit.sh
