name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ min ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.18

    - name: Vet
      working-directory: claat
      run: go vet ./...

    - name: Build
      working-directory: claat
      run: go build -v ./...

    - name: Test
      working-directory: claat
      run: go test -v ./...
